#include <CoreFoundation/CoreFoundation.h>
#include <CoreServices/CoreServices.h>
#include <CoreText/CoreText.h>
#include <CoreGraphics/CoreGraphics.h>
#include <CoreData/CoreData.h>
#include <CoreImage/CoreImage.h>
#include <CoreMedia/CoreMedia.h>
#include <CoreAudio/CoreAudio.h>
#include <CoreVideo/CoreVideo.h>
#include <Security/Security.h>
#include <CFNetwork/CFNetwork.h>
#include <Network/Network.h>
#include <Cocoa/Cocoa.h>
#include <Carbon/Carbon.h>
#include <Foundation/Foundation.h>
#include <ApplicationServices/ApplicationServices.h>
#include <AppKit/AppKit.h>
#include <AVFAudio/AVFAudio.h>
#include <AudioToolbox/AudioToolbox.h>
#include <VideoToolbox/VideoToolbox.h>
#include <Accelerate/Accelerate.h>
#include <Metal/Metal.h>
#include <MetalKit/MetalKit.h>
#include <AVFoundation/AVFoundation.h>
#include <AVKit/AVKit.h>
#include <Accounts/Accounts.h>
#include <AddressBook/AddressBook.h>
#include <AppleScriptObjC/AppleScriptObjC.h>
#include <AudioUnit/AudioUnit.h>
#include <AudioVideoBridging/AudioVideoBridging.h>
#include <Automator/Automator.h>
#include <BusinessChat/BusinessChat.h>
#include <CHIP/CHIP.h>
#include <CloudKit/CloudKit.h>
#include <Contacts/Contacts.h>
#include <ContactsUI/ContactsUI.h>
#include <CoreAudioKit/CoreAudioKit.h>
#include <CoreBluetooth/CoreBluetooth.h>
#include <CoreLocation/CoreLocation.h>
#include <CoreMIDI/CoreMIDI.h>
#include <CoreMediaIO/CMIOHardware.h>
#include <CoreSpotlight/CoreSpotlight.h>
#include <CryptoTokenKit/CryptoTokenKit.h>
#include <DVDPlayback/DVDPlayback.h>
#include <DirectoryService/DirectoryService.h>
#include <EventKit/EventKit.h>
#include <FWAUserLib/FWAUserLib.h>
#include <FinderSync/FinderSync.h>
#include <ForceFeedback/ForceFeedback.h>
#include <GLKit/GLKit.h>
#include <GameController/GameController.h>
#include <GameKit/GameKit.h>
#include <GameplayKit/GameplayKit.h>
#include <ICADevices/ICADevices.h>
#include <ImageCaptureCore/ImageCaptureCore.h>
#include <InstallerPlugins/InstallerPlugins.h>
#include <Intents/Intents.h>
#include <IntentsUI/IntentsUI.h>
#include <LDAP/ldap.h>
#include <LocalAuthentication/LocalAuthentication.h>
#include <LocalAuthenticationEmbeddedUI/LocalAuthenticationEmbeddedUI.h>
#include <MailKit/MailKit.h>
#include <MapKit/MapKit.h>
#include <MediaAccessibility/MediaAccessibility.h>
#include <MediaPlayer/MediaPlayer.h>
#include <MediaToolbox/MediaToolbox.h>
#include <MetalPerformanceShaders/MetalPerformanceShaders.h>
#include <Network/Network.h>
#include <NetFS/NetFS.h>
#include <NetworkExtension/NetworkExtension.h>
#include <NotificationCenter/NotificationCenter.h>
#include <OpenAL/OpenAL.h>
#include <OpenCL/opencl.h>
#include <OpenDirectory/OpenDirectory.h>
#include <OpenGL/OpenGL.h>
#include <PHASE/PHASE.h>
#include <Photos/Photos.h>
#include <PreferencePanes/PreferencePanes.h>
#include <Python/Python.h>
#include <QuartzCore/QuartzCore.h>
#include <QuickLook/QuickLook.h>
#include <SafariServices/SafariServices.h>
#include <SceneKit/SceneKit.h>
#include <ScreenSaver/ScreenSaver.h>
#include <ScriptingBridge/ScriptingBridge.h>
#include <ServiceManagement/ServiceManagement.h>
#include <ShazamKit/ShazamKit.h>
#include <Social/Social.h>
#include <StoreKit/StoreKit.h>
#include <SystemConfiguration/SystemConfiguration.h>
#include <TWAIN/TWAIN.h>
#include <Tcl/tcl.h>
#include <Vision/Vision.h>
#include <WebKit/WebKit.h>
#include <vmnet/vmnet.h>
#include <AGL/agl.h>
#include <Collaboration/Collaboration.h>
#include <CoreML/CoreML.h>
#include <NaturalLanguage/NaturalLanguage.h>
#include <CoreWLAN/CoreWLAN.h>
#include <DiskArbitration/DiskArbitration.h>
#include <ExceptionHandling/ExceptionHandling.h>
#include <ExternalAccessory/ExternalAccessory.h>
#include <Hypervisor/hv.h>
#include <ImageIO/ImageIO.h>
#include <InputMethodKit/InputMethodKit.h>
#include <InstantMessage/IMAVControl.h>
#include <InstantMessage/IMAVManager.h>
#include <InstantMessage/IMService.h>
#include <IMServicePlugIn/IMServicePlugIn.h>
#include <IMServicePlugIn/IMServicePlugInFileTransfer.h>
#include <IMServicePlugIn/IMServicePlugInFileTransferSession.h>
#include <IMServicePlugIn/IMServicePlugInFileTransferSessionSupport.h>
#include <JavaScriptCore/JavaScriptCore.h>
#include <LDAP/ldap.h>
#include <LDAP/lber.h>
#include <LatentSemanticMapping/LatentSemanticMapping.h>
#include <MediaLibrary/MediaLibrary.h>
#include <MultipeerConnectivity/MultipeerConnectivity.h>
#include <OSAKit/OSAKit.h>
#include <OpenCL/opencl.h>
#include <PCSC/winscard.h>
#include <PhotosUI/PhotosUI.h>
#include <Quartz/Quartz.h>
#include <SecurityFoundation/SecurityFoundation.h>
#include <SpriteKit/SpriteKit.h>
#include <SyncServices/SyncServices.h>
#include <Tcl/tcl.h>
#include <VideoDecodeAcceleration/VDADecoder.h>
#include <VideoSubscriberAccount/VideoSubscriberAccount.h>
#include <AdSupport/AdSupport.h>
#include <UserNotifications/UserNotifications.h>
#include <iTunesLibrary/iTunesLibrary.h>
#include <MetricKit/MetricKit.h>
#include <Speech/Speech.h>
#include <LinkPresentation/LinkPresentation.h>
#include <OSLog/OSLog.h>
#include <DeviceCheck/DeviceCheck.h>
#include <BackgroundTasks/BackgroundTasks.h>
#include <QuickLookThumbnailing/QuickLookThumbnailing.h>
#include <PencilKit/PencilKit.h>
#include <FileProvider/FileProvider.h>
#include <IdentityLookup/IdentityLookup.h>
#include <ExecutionPolicy/ExecutionPolicy.h>
#include <SwiftUI/SwiftUI.h>
#include <FileProviderUI/FileProviderUI.h>
#include <AuthenticationServices/AuthenticationServices.h>
#include <PushKit/PushKit.h>
#include <CoreAudioTypes/CoreAudioTypes.h>
#include <CoreHaptics/CoreHaptics.h>
#include <CallKit/CallKit.h>
#include <CoreMotion/CoreMotion.h>
#include <SoundAnalysis/SoundAnalysis.h>
#include <AutomaticAssessmentConfiguration/AutomaticAssessmentConfiguration.h>
#include <JavaRuntimeSupport/JavaRuntimeSupport.h>
#include <JavaNativeFoundation/JavaNativeFoundation.h>
#include <UserNotificationsUI/UserNotificationsUI.h>
#include <ScreenTime/ScreenTime.h>
#include <MLCompute/MLCompute.h>
#include <UniformTypeIdentifiers/UniformTypeIdentifiers.h>
#include <ParavirtualizedGraphics/ParavirtualizedGraphics.h>
#include <SensorKit/SensorKit.h>
#include <ReplayKit/ReplayKit.h>
#include <ClassKit/ClassKit.h>
#include <MetalPerformanceShadersGraph/MetalPerformanceShadersGraph.h>
#include <KernelManagement/KernelManagement.h>
#include <NearbyInteraction/NearbyInteraction.h>
#include <Accessibility/Accessibility.h>
#include <AppTrackingTransparency/AppTrackingTransparency.h>
#include <WidgetKit/WidgetKit.h>
#include <PassKit/PassKit.h>
#include <Virtualization/Virtualization.h>
#include <IOSurface/IOSurface.h>
#include <IOBluetooth/IOBluetooth.h>
#include <IOBluetoothUI/IOBluetoothUI.h>
#include <DriverKit/DriverKit.h>
#include <SystemExtensions/SystemExtensions.h>
