TIL_NAME = libstl_cpp
TIL_DESC = "Linux stl"
INPUT_FILE = stl_example.h
# KERNEL_HEADERS = /usr/src/linux-headers-5.11.0-41-generic
CLANG_ARGV = -target x86_64-pc-linux-gnu                               \
             -x c++                                                 \
             -isystem /usr/lib/gcc/x86_64-linux-gnu/9/include

include ../idaclang.mak
